/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IBlockEditor, IToolbarBase, IToolbarConfigKeys } from "@swc-editor/core";
export { IBlockEditor, IToolbarBase, IToolbarConfigKeys } from "@swc-editor/core";
export namespace Components {
    interface SwcIconSvg {
        "icon": string;
    }
    interface SwcToolbar {
        "config": IToolbarConfigKeys;
        "editor": IBlockEditor;
    }
    interface SwcToolbarButton {
        "config": IToolbarBase;
        "editor": IBlockEditor;
    }
}
declare global {
    interface HTMLSwcIconSvgElement extends Components.SwcIconSvg, HTMLStencilElement {
    }
    var HTMLSwcIconSvgElement: {
        prototype: HTMLSwcIconSvgElement;
        new (): HTMLSwcIconSvgElement;
    };
    interface HTMLSwcToolbarElement extends Components.SwcToolbar, HTMLStencilElement {
    }
    var HTMLSwcToolbarElement: {
        prototype: HTMLSwcToolbarElement;
        new (): HTMLSwcToolbarElement;
    };
    interface HTMLSwcToolbarButtonElement extends Components.SwcToolbarButton, HTMLStencilElement {
    }
    var HTMLSwcToolbarButtonElement: {
        prototype: HTMLSwcToolbarButtonElement;
        new (): HTMLSwcToolbarButtonElement;
    };
    interface HTMLElementTagNameMap {
        "swc-icon-svg": HTMLSwcIconSvgElement;
        "swc-toolbar": HTMLSwcToolbarElement;
        "swc-toolbar-button": HTMLSwcToolbarButtonElement;
    }
}
declare namespace LocalJSX {
    interface SwcIconSvg {
        "icon"?: string;
    }
    interface SwcToolbar {
        "config"?: IToolbarConfigKeys;
        "editor"?: IBlockEditor;
    }
    interface SwcToolbarButton {
        "config"?: IToolbarBase;
        "editor"?: IBlockEditor;
    }
    interface IntrinsicElements {
        "swc-icon-svg": SwcIconSvg;
        "swc-toolbar": SwcToolbar;
        "swc-toolbar-button": SwcToolbarButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "swc-icon-svg": LocalJSX.SwcIconSvg & JSXBase.HTMLAttributes<HTMLSwcIconSvgElement>;
            "swc-toolbar": LocalJSX.SwcToolbar & JSXBase.HTMLAttributes<HTMLSwcToolbarElement>;
            "swc-toolbar-button": LocalJSX.SwcToolbarButton & JSXBase.HTMLAttributes<HTMLSwcToolbarButtonElement>;
        }
    }
}
